#!/usr/bin/env bash

# remove the lock file if it exists
if [ -e /data/db/mongod.lock ]; then
    exec s6-setuidgid mongodb rm /data/db/mongod.lock
fi

# run mongod as mongodb user
exec s6-setuidgid mongodb mongod;
